# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.0.0
  hooks:
    - id: end-of-file-fixer
    - id: check-added-large-files
    - id: check-byte-order-marker
    - id: check-case-conflict
    - id: check-executables-have-shebangs
    - id: check-merge-conflict
    - id: detect-aws-credentials
    - id: detect-private-key
    - id: trailing-whitespace
- repo: https://github.com/Lucas-C/pre-commit-hooks
  rev: v1.1.6
  hooks:
    - id: forbid-tabs
      exclude: (Makefile|debian/rules)(\.in)?$
    - id: forbid-crlf
      exclude: (Makefile|debian/rules)(\.in)?$
- repo: https://github.com/syntaqx/git-hooks
  rev: v0.0.16
  hooks:
    - id: forbid-binary
